### ISSUE TITLE
MFA QR code not readable

### ISSUE THREAD

**Issue by zud222** [tine-groupware/tine#22]
Hi,

When I register a new TOTP MFA method, a secret key is generated and displayed as QR code. However, the code is not readable by any app (even after zooming in) or online scanner. See sample file:
![qr_not_working](https://github.com/tine-groupware/tine/assets/63943320/9b7c5cd7-545c-46f2-85d0-5db7769d320f)

**Comment by pschuele** [comment]
yup, seems to be a problem with the device, not with the code

**Comment by corneliusweiss** [comment]
Hey, for me it's working as well (using ms authenticator (by cam) and opt-manager (with your image)
pls try an other phone
