### ISSUE TITLE
Change from old community version to this version

### ISSUE THREAD

**Issue by hartundweich** [tine-groupware/tine#29]
Hi,
Last days I noticed, that the old community repo is not beeing maintained anymore - so i decided to use the releases on the new tine-groupware repo.
I updated my tine installation to the latest community release (2023.12.1) without any problems.
So what next? Should 2023.11.6 run as an update to my version? Today I gave it a short try, but the update failed... 
Should I start with updating to 2023.11.1 and go forward to 2023.11.6? 
Please give me a hint - if it should be possible to take my community edition version 2023.12.1 to 2023.11.6 tine-groupware than I'll post further information what is failing - maybe I copy my setup to a testing instance so we can work it out.. 
It would be nice if you could tell me what is the best way to get my 2023.12.1 community edition to an actual working version

**Comment by lab-at-nohl** [comment]
YES. 

I came from 2023.12.1 to 2023.11.3 flawlessly. But should work directly to any 2023.11.y version. After you are on 2022.11.y path you're save for future.

**Comment by hartundweich** [comment]
Closing as solved - it was my database....
