### ISSUE TITLE
Dokumentation - Operator - Datenbankvergleich

### ISSUE THREAD

**Issue by hartundweich** [tine-groupware/tine#30]
Hallo,

in diesem Dokumentationslink https://tine-docu.s3web.rz1.metaways.net/operators/howto/tine20AdminDatabase/ verweist ihr beim Punkt "DB-Schema Vergleich und Aktualisierung" hinsichtlich einer einzuspielenden Datei (tine20/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractAsset.php) auf einen Link den es nicht mehr gibt: https://forge.tine20.org/view.php?id=13702

Gibt es die geptachte Datei irgendwo oder ist diese Info hinfällig? 

Ich bin da drüber gestolpert, weil ich grade dabei bin von Community auf die aktuelle Version 2023.11.6 zu wechseln.

**Comment by lab-at-nohl** [comment]
Ich würde erst mal mit einem Log File und einen manuellen Abgleich starten...

**Comment by hartundweich** [comment]
Wie funktioniert der manuelle Abgleich? Mein Logfile hat keine Fehler, aber beim Update von 2023.12.1 Community auf die aktuelle 2023.11.6 haut es mit dem DB Update nicht hin. Tinebase krieg ich upgedatet, beim Calendar hakt es wieder mal mit Foreignkeys beim Alter Table…
Von daher hätte ich gern mal die Struktur meiner Datenbank geprüft und entsprechend aktualisiert. Meine Installation ist über 10 Jahre alt, von daher kann schon sein, dass da was nicht passt.

**Comment by lab-at-nohl** [comment]
Manuell meine ich, Log während Setup schreiben. Dann sehen wo es hängt. Und dann gezielt mit einer frischen Installation abgleichen. Und dann entweder Posten hier oder probieren, Setup anzupassen 🤡

**Comment by hartundweich** [comment]
Jupp ich weiß schon was du meinst... vieles kann ich selbst beheben - aber bei dem hier steh ich an:

8e8d12 - setupuser - 2024-03-27T09:47:21+00:00 ERR (3): Setup_Controller::updateApplications::706 An exception occurred while executing 'ALTER TABLE tine20_cal_attendee ADD CONSTRAINT FK_18666BE8C7A66CD4 FOREIGN KEY (cal_event_id) REFERENCES tine20_cal_events (id) ON DELETE CASCADE':

SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`tine`.`#sql-fd2_10e73`, CONSTRAINT `FK_18666BE8C7A66CD4` FOREIGN KEY (`cal_event_id`) REFERENCES `tine20_cal_events` (`id`) ON DELETE CASCADE)

Eine Idee wo ich da ansetzen kann? Mit foreign keys hab ich's leider nicht so :-(

**Comment by hartundweich** [comment]
OK ich habs gerafft... da gab es in der cal_attendee table Datensätze für die es kein cal_event gab... Update läuft jetzt durch - HURRAA
