### ISSUE TITLE
Frage zu User-Account Anzahl

### ISSUE THREAD

**Issue by hartundweich** [tine-groupware/tine#31]
Hallo,

da sich ja jetzt mit der Auflassung der Community Version hinsichltich Lizenzierung Änderungen ergeben haben wollte ich mal fragen ob folgende User-Accounts, die vom System scheinbar automatisch eingerichtet worden sind zu der Gesamtzahl 5 zählen bis zu denen Tine nach wie vor als Open Source Software für den Privatgebraucht zur Verfügung steht.

Ich hab da folgende Systemuser: 

- anonymoususer
- cronuser
- replicationuser
- setupuser

Diese User sind alle als "Deaktiviert" gekennzeichnet. Zusätzlich hab ich noch 4 private User, die das System verwenden... sollte also meiner Meinung alles im grünen Bereich sein? 

Was mich etwas beunruhigt: Ich habe als Admin rechts oben stehen: "Ihre tine Lizenz ist abgelaufen"

Ich konnte jetzt aber problemlos zu meinen bestehenden 4 Usern nochmal 3 anlegen und mich mit denen auch anmelden... wo kommt denn die 5er Beschränkung denn nun genau zum Tragen?

**Comment by lab-at-nohl** [comment]
Welcher Account dazuzählt, muss ich erst rausfinden. Muss man ja im Quellcode sehen können. 

Generell ist das ein gutes Thema für die Diskussionen. Es ist ja kein issue. 

Was die Auswirkung einer fehlenden Lizenz ist, habe ich versucht dort in Frage 3 zusammenzufassen (siehe auch die Fußnote). Gerne einfach eine weitere Frage aufmachen. 
https://github.com/orgs/tine-groupware/discussions/19

**Comment by JPRuehmann** [comment]
3User + 3Mail Accounts und einige Zusatzkomponenten lassen sich nicht installieren z.B. das User Manual.
Hingewiesen wird mann darauf nirgends (weder in der UI noch in der setup.php.

Ich werde in den sauren Apfel beissen und zu Google wechseln.

**Comment by hartundweich** [comment]
> 3User + 3Mail Accounts und einige Zusatzkomponenten lassen sich nicht installieren z.B. das User Manual. Hingewiesen wird mann darauf nirgends (weder in der UI noch in der setup.php.
> 
> Ich werde in den sauren Apfel beissen und zu Google wechseln.

damit komm ich aus... ich hab hier nur 3 Mailkonten zu verwalten...

Die Frage die sich aber stellt: was ist mit den ganzen Systemusern die ich hab? anonymoususer, setupuser, cronuser, replicationuser - die sind inaktiv gestellt
Und ich hab hier noch einen lokalen Admin-User um die Instanz zu administrieren, der hat aber kein E-Mail Konto... 
Bis jetzt konnte ich noch nicht feststellen, dass etwas nicht klappt.. 
Wo im Quellcode hast du die Limitierung  gefunden?

**Comment by JPRuehmann** [comment]
Die werden bei mir zumindest nicht mitgezählt. Bei mir gibt es nur zwei aktive user (JPRuehmann und Administrator).

**Comment by lab-at-nohl** [comment]
Oben hatte ich schon auf meine Frage/Antwort 3 und die Fußnote eines Beitrags von mir hingewiesen. Nur, um keine Mißverständnisse aufkommen zu lassen: 

- Die Benutzerbeschränkung (die Lizenz, die man erwerben kann) bezieht sich nur auf einzelne Apps. Hauptsächlich Spezialanwendungen. Welche das aktuell sind bzw. ab welcher Version habe ich dort zusammengefasst. (kann man ja im Quellcode problemlos nachlesen) 
- Die Apps der alten Community Edition (Adressbuch, Kalender, Mail, ActiveSync u.a.) sind alle weiter ohne Beschränkung. Also auch mit zweistelligen Nutzerzahlen (kann ich bestätigen!). Mit wäre nicht bekannt, dass sich das ändern soll. 
- Für die allermeisten Nutzer in Webhosting-Umgebungen gibt es keinerlei Veränderung. Außer, dass man jetzt wieder schnelle Updates bekommt (nicht nur weeklys, sondern das was zuvor nur an Businesskunden ausgespielt wurde). Klare Verbesserung!!

https://github.com/orgs/tine-groupware/discussions/19

Von daher wäre eigentlich Partystimmung angemessen. 🥇

**Comment by JPRuehmann** [comment]
Bei mir funkrionieren Mail und CalDav nicht mehr. Mit dem Sourcecode ken kein normaler Nutzer etwas anfangen. Die Hinweise zu den Begrenzungen sollte offen in der Setup.php zu finden sein (App Verwaltung).

**Comment by hartundweich** [comment]
Ich glaub wir können das mal schließen?
