### ISSUE TITLE
Installation ohne "CREATE USER" (Setupuser) Recht?

### ISSUE THREAD

**Issue by JPRuehmann** [tine-groupware/tine#36]
Gibt es eine Möglichkeit Tine ohne Setupuser zu installieren?
Mein Hoster (All-Inkl) gibt mir das Recht CREATE USER nicht.
Die Zugangsdaten zur Erstellung der Datenbank selber funktionieren nicht für den Setupuser.

**Comment by JPRuehmann** [comment]
Vergessen wir es Tine ist eh nicht mehr zu gebrauchen. Ich werde meine Kontakte und zu synchronisierenden Dateien auf Google transferieren und Tine dann löschen.
Ich sehe nicht ein als Einzelnutzer Monatlich Mehr als für alles andere zu bezahlen nur weil ich mehr als 3 eMail Accounts habe.

Ich wünsche euch noch viel Erfolg.

**Comment by lab-at-nohl** [comment]
> Ich sehe nicht ein als Einzelnutzer Monatlich Mehr als für alles andere zu bezahlen nur weil ich mehr als 3 eMail Accounts habe. 

Das ist nicht der Fall. Die meisten Apps sind beliebig weiter nutzbar... Einschließlich Mail, Kalender, Kontakte und ActiveSync.

**Comment by JPRuehmann** [comment]
Bei mir nicht.
