### ISSUE TITLE
Set Logtime to local time

### ISSUE THREAD

**Issue by mokraemer** [tine-groupware/tine#44]
At the moment loggin is done with a timestamp set to UTC. This is irritating, as system logs are shown/converted to the local time.
At least the default should be local time, not UTC

**Comment by mokraemer** [comment]
still relevant

**Comment by mokraemer** [comment]
still relevant

**Comment by pschuele** [comment]
the logger timezone can be configured via the 'tz' option:

~~~php
'logger' => [
  'tz' => 'America/Los_Angeles',
// [...]
]
~~~

see https://www.php.net/manual/de/function.date-default-timezone-set.php for supported timezones...

**Comment by pschuele** [comment]
we could also think about adding a "detect/auto" option (ini_get('date.timezone')).

**Comment by mokraemer** [comment]
sure. In php it is mandatory to set the timezone

**Comment by mokraemer** [comment]
php -r "echo ini_get('date.timezone');"
Europe/Berlin
