### ISSUE TITLE
Textpart of Appointment missing

### ISSUE THREAD

**Issue by mokraemer** [tine-groupware/tine#46]
Calendar entries sent by mail contain the ics file. But additionally there could/should be a text part inside the mail.
Tine 15.x generated a part:
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: quoted-printable
"details for the appointment"

which contained the information which could be read by any mail client not using the ics file.

This was very helpfull for many users.

**Comment by mokraemer** [comment]
still relevant

**Comment by mokraemer** [comment]
still relevant

**Comment by pschuele** [comment]
I'll have a look, should be easy to implement

**Comment by pschuele** [comment]
hmm, but there is a textpart in the message? :thinking: 

just tested in my local dev environment...

``
--=_245b52f8e5a143975f002632275b6d6e
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

=0ALink: http://127.0.0.1:4000/#/Calendar/Event/467b9adb0c45a435af12259d=
599d630ca9469d98=0A=0ATermin Details:=0AStart:              Freitag, 20.=
09.2024 12:00:00=0AEnde:               Freitag, 20.09.2024 15:15:00=0ATh=
ema:              testssss=0ATeilnehmer/in:=0A    Admin, tine =C2=AE (Er=
forderlich, Zugesagt) =0A=0A
