### ISSUE TITLE
Why you have not done a transfer directly the repository instead of a fork?

### ISSUE THREAD

**Issue by Neustradamus** [tine-groupware/tine#5]
Dear @tine-groupware, @pschuele,

Why you have not done a transfer instead of a fork of the original repository?
- https://github.com/tine20/tine20

Thanks in advance.

**Comment by pschuele** [comment]
hi Neustradamus,
I'm also not quite convinced that the forking was a good idea. I remember that we had reasons for this, but it does not make sense to me now either... I think, we should unfork (https://stackoverflow.com/questions/38831301/how-to-un-fork-the-github-repository).
@byteplow do you have an opinion on this?

**Comment by Neustradamus** [comment]
The solution is to unarchive the original place, merge all in upstream.

Now there are two possibilities after the first previous step.

First:
- Move all repositories from "tine-groupware" into "tine20" original organization
- Rename this current organization to another name temp
- Rename the original organization with the "tine-groupware", and rename the current "temp" organization to "tine20"
- Edit the new "tine20" description to inform people to go "tine-groupware" organization

Second:
- Remove the current fork or move into another place
- Move all repositories from "tine20" to "tine-groupware" organization
- Update "tine20" description to inform people to go "tine-groupware" organization

**Comment by byteplow** [comment]
Definitely unhappy with forking. We should unfork. But I am not sure we should transfer the repo. We had some reasons not to. But I do not really remember what they were. @pschuele let us discuss this on wensday.
One of the reasons was to lose the old issues. A lot of them are outdated. But there should be a better way to solve this. Like closing them with a stall bot. Also not a grade, but better than just ignoring / deleting them all.

**Comment by pschuele** [comment]
we'll just detach the fork. the other repos from the original namespace will be transferred/archived soon.

**Comment by pschuele** [comment]
fork as been detached. thx @githubsupport

**Comment by Neustradamus** [comment]
@pschuele: I think that the best solution is to unarchive the original place, and merge all changes in upstream...

Why?
Please look "Watching", "Fork", "Star" parts.

**Comment by Neustradamus** [comment]
@pschuele: Very bad point...

Can you:
- Rename temporarly, this tine to tine-temp?
- Rename https://github.com/tine20/tine20 to https://github.com/tine20/tine
Transfer https://github.com/tine20/tine to here?

Add all the new changes into https://github.com/tine-groupware/tine-temp to https://github.com/tine-groupware/tine

Transfer the "Issues" into the good repo, and inform people which has done PR to do in the good repo?

Thanks in advance.

**Comment by Neustradamus** [comment]
I was very simple but I am not sure that github support can re-attach you now...
