### ISSUE TITLE
VCF Import?

### ISSUE THREAD

**Issue by JPRuehmann** [tine-groupware/tine#54]
Is tere a Way to import VCF Files?
Thanks.

**Comment by pschuele** [comment]
hi JP,
sorry for the late reply: yes, you can import vcf files from the addressbook gui:
(select "VCARD-Import für Kontakte"):

![Screenshot from 2024-09-25 17-41-38](https://github.com/user-attachments/assets/58f9c7b9-8f0e-4b28-9c08-0ed7b2334c2d)
