### ISSUE TITLE
You need to run webpack-dev-server in dev mode!

### ISSUE THREAD

**Issue by JPRuehmann** [tine-groupware/tine#67]
Ich habe gerade die neue Version von Tine installiert (weekly-2024.30.1).
Wenn ich die setup.php aufrufe erhalte ich nur folgende Meldung (You need to run webpack-dev-server in dev mode! See https://wiki.tine20.org/Developers/Getting_Started/Working_with_GIT#Install_webpack ). Wenn ich versuche den Link aufzurufen (https://wiki.tine20.org/Developers/Getting_Started/Working_with_GIT#Install_webpack) erhalte ich folgende Meldung (Seite wurde nicht gefunden). wie kriege ich das ans laufen?

**Comment by ignoreigor** [comment]
Hallo,

dieser Fehler erscheint bei mir nicht. Sourcen-Paket bei den Assets erwischt?

**Comment by JPRuehmann** [comment]
Nein,

Da gibt es kein Sourcen-Packet.

https://github.com/tine-groupware/tine/releases/download/weekly-2024.30.1/weekly-2024.30.1.tar.bz2

**Comment by ignoreigor** [comment]
Kann sein, wie Du sagst. Paket ist richtig, allerdings bin ich beim Update auf Elli gerutscht. Nun muss ich erstmal aufräumen, damit irgendwas wieder geht.

**Comment by ignoreigor** [comment]
Confirmed! 
Da scheint irgendeine Konstante noch auf Development gesetzt zu sein. Das geht bestimmt eleganter, aber Du könntest

Tinebase/Core.php:700 mit 
`define('TINE20_BUILDTYPE', 'RELEASE');`
überschreiben. Danach sollte es starten.

**Comment by JPRuehmann** [comment]
Danke, das war es.
Hoffen wir das das nächste Woche nicht wieder passiert.
