### ISSUE TITLE
can't re-open bug

### ISSUE THREAD

**Issue by mokraemer** [tine-groupware/tine#70]
Currently all bugs are closed and can't be reopend, even if the issue is not resolved.

**Comment by mokraemer** [comment]
ping

**Comment by pschuele** [comment]
ah I see, you can only re-open if you closed the issue ... https://stackoverflow.com/questions/21333654/how-to-re-open-an-issue-in-github

we already increased the stale/close timers:
~~~
          days-before-stale: 90
          days-before-close: 30
~~~

I'll re-open your issue #56 .
are there more that need to be re-opened?

**Comment by pschuele** [comment]
done
